version: '3.1'

services:
  tomcat:
    container_name: appbase-tomcat
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports: 
      - "18080:8080"
    restart: "no"
    depends_on:
      - postgres
  postgres:
    container_name: appbase-postgres
    image: postgres:9.1.19
    ports:
      - "15432:5432"
    restart: "no"
    environment:
      POSTGRES_USER: fql
      POSTGRES_PASSWORD: fql
      POSTGRES_DB: appbase
    volumes:
      - ./.postgres:/var/lib/postgresql/data
      
